In [1]:
import numpy as np

In [2]:
var1=np.array([1,2,3,4])

In [3]:
var1

array([1, 2, 3, 4])

In [4]:
type(var1)

numpy.ndarray

In [5]:
var1.dtype

dtype('int32')

In [6]:
varA=[1,1.1,2]
var2=np.array(varA)

In [7]:
var2

array([1. , 1.1, 2. ])

In [8]:
var2.dtype

dtype('float64')

In [9]:
var2.shape

(3,)

In [10]:
var3=np.array([[1.5,2.5],[3.4]], dtype=object)

In [11]:
var3

array([list([1.5, 2.5]), list([3.4])], dtype=object)

In [12]:
var3=np.array([[1.5,2.5],[3,4]], dtype=object)

In [13]:
var3

array([[1.5, 2.5],
       [3, 4]], dtype=object)

In [14]:
var3.shape

(2, 2)

In [15]:
var3[0]

array([1.5, 2.5], dtype=object)

In [16]:
var3[0,0]

1.5

In [17]:
var3[-1,-1]

4

In [18]:
var3[-1,0]='Aghniya'

In [19]:
var3

array([[1.5, 2.5],
       ['Aghniya', 4]], dtype=object)

### Alokasi dan Random Array

In [20]:
varA=np.empty(3)

In [21]:
varA

array([1. , 1.1, 2. ])

In [22]:
varB=np.empty((3,2))

In [23]:
varB

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
5*0.001

0.005

In [25]:
5*1e-3

0.005

In [26]:
varB=np.zeros((3,2))

In [27]:
varB

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
varc=np.empty((10,10))

In [29]:
varc

array([[1.12249919e-311, 1.12249919e-311, 1.12249919e-311,
        1.12249919e-311, 1.12249919e-311, 1.12249919e-311,
        1.12249919e-311, 1.12249919e-311, 1.12249919e-311,
        1.12249919e-311],
       [1.12249919e-311, 1.12249949e-311, 1.12249919e-311,
        1.12249919e-311, 1.12249919e-311, 1.12249919e-311,
        1.12249919e-311, 1.12249919e-311, 1.12249919e-311,
        1.12249919e-311],
       [1.12249919e-311, 1.12249919e-311, 1.12249919e-311,
        1.12249919e-311, 1.12249919e-311, 1.12249926e-311,
        1.12249919e-311, 1.12249919e-311, 1.12249919e-311,
        1.12249940e-311],
       [1.12250682e-311, 1.12252583e-311, 1.12250721e-311,
        1.12252583e-311, 1.12250739e-311, 1.12250738e-311,
        1.12252583e-311, 1.12250683e-311, 1.12252515e-311,
        1.12250738e-311],
       [1.12250680e-311, 1.12250680e-311, 1.12250682e-311,
        1.12250682e-311, 1.12252583e-311, 1.12252583e-311,
        1.12250681e-311, 1.12252583e-311, 1.12250682e-311,
        1.1

In [30]:
varD=np.ones((5,3))

In [31]:
varD

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
varE=np.arange(1,5)

In [33]:
varE

array([1, 2, 3, 4])

In [34]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [35]:
varMin=1
varMax=10
varDelta=2
np.arange(varMin,varMax,varDelta)

array([1, 3, 5, 7, 9])

In [36]:
np.arange(10,2,-2)

array([10,  8,  6,  4])

### Random Numpy

In [37]:
np.random.random(3)

array([0.0042747 , 0.46877125, 0.74390686])

In [41]:
np.random.random((3,2))

array([[0.27771588, 0.19365353],
       [0.52125073, 0.95305261],
       [0.91825256, 0.61394958]])